In [23]:
inputs = [ 1, 2, 3, 2.5 ]
weights = [[ 0.2, 0.8,- 0.5,1],[ 0.5, -0.91, 0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
biases = [ 2 , 3 , 0.5]

layer_outputs = []

for neuron_weight, n_biases in zip(weights, biases):
    neuron_output=0
    for n_input, n_weight in zip(inputs, neuron_weight):
        neuron_output += n_input*n_weight
    #add bias    
    neuron_output += n_biases
    #call empty list and add those
    layer_outputs.append(neuron_output)
    
print(layer_outputs)

[4.8, 1.21, 2.385]


In [36]:
#array 
a=[[[2,4,6,1],
   [2,3,6,2]],
   [[12,3,4,6],
   [1,4,4,6]],
   [[3,4.5,6,2],
   [2,3,4,1]]]

#3 dimnsion, 2 list and 4 element 

In [44]:
len(a)
# a.shape

2

In [34]:
#python a 1-dimensional array represent an array

In [8]:
# First layer with Numpy library
inputs = [ 1, 2, 3, 2.5 ]
weights = [[ 0.2, 0.8,- 0.5,1],
           [ 0.5, -0.91, 0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]
biases = [ 2 , 3 , 0.5]

In [9]:
import numpy as np

In [14]:
# output =np.dot(inputs,weights)+biases #not working
output =np.dot(weights,inputs)+biases
print(output)

[4.8   1.21  2.385]


In [64]:
a = [2, 3, 4]

In [21]:
a=np.array([[2,3,4,5]])   
#array not first dimension in python bcoz first dimension in python is list

In [22]:
a.shape

(1, 4)

In [24]:
b=np.array([a])

In [26]:
print(b.shape)
print(b)

(1, 1, 4)
[[[2 3 4 5]]]


In [29]:
b=np.expand_dims(np.array(a), axis=0)

In [30]:
b.shape

(1, 1, 1, 4)

In [33]:
b

array([[[[2, 3, 4, 5]]]])

In [68]:
a=[2,3,4]
b=[4,7,2]

In [69]:
np.dot(a,b)

37

In [70]:
a=np.array([a])
b=np.array([b]).T

In [71]:
a=np.dot(a,b)

In [72]:
a.shape

(1, 1)

In [73]:
a

array([[37]])

### SortCut Way

In [77]:
inputs = [ [1, 2, 3, 2.5],[1,4,5,6],[2,5,7,2]]
weights = [[ 0.2, 0.8,- 0.5,1],[ 0.5, -0.91, 0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
biases = [ 2 , 3 , 0.5]

In [78]:
np.dot(inputs, np.array(weights).T)+biases   

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.84 ,  5.23 ],
       [ 4.9  ,  0.27 ,  1.56 ]])